package com.plugtree.rules

import com.plugtree.dslExample.entities.*

rule "expense greater than 1000"
when
	$customer : Customer( expense > 1000 );
then
	$customer.setDiscount(getDiscount($customer.getExpense(), 10));
end

rule "Registered customer"
when
	$customer : Customer( registered == true )
then
	$customer.setDiscount(getDiscount($customer.getExpense(), 5));
end

function Double getDiscount(Double expense, int discount){
    return (expense * discount) / 100;
}

