package com.plugtree.rules

import com.plugtree.dslExample.entities.*

rule "expense greater than 1000"
when
	$customer : Customer( expense > 1000,  registered == false);
then
	$customer.setDiscount(getDiscount($customer.getExpense(), 10));
end

rule "Registered customer and expense greater than 1000"
when
	$customer : Customer( registered == true, expense > 1000)
then
	$customer.setDiscount(getDiscount($customer.getExpense(), 15));
end

function Double getDiscount(Double expense, int discount){
    return (expense * discount) / 100;
}

